### PR TITLE
neonvm: Update VM's .Status.PodName immediately on API server

### LINKED ISSUE #794: Bug: NeonVM controller creates more than one pod for a VM
## Environment

Local

## Steps to reproduce

```console
$ kubectl apply -f vm-deploy.yaml
virtualmachine.vm.neon.tech/postgres14-disk-test created

$ kubectl get pods
NAME                                 READY   STATUS    RESTARTS   AGE
postgres14-disk-test-g5qvs           2/2     Running   0          2m26s

$ kubectl delete pod postgres14-disk-test-g5qvs
pod "postgres14-disk-test-g5qvs" deleted

$ kubectl get pods
NAME                                 READY   STATUS    RESTARTS   AGE
postgres14-disk-test-rgv6t           2/2     Running   0          28s
postgres14-disk-test-jcxsd           2/2     Running   0          28s
```

## Expected result

Seeing one pod after deleting the first one.

## Actual result

Two pods are running for the same VM.

## Why this happens?

Running two reconcile jobs for the same VM might lead to this situation. This is a classic race condition. This problem has always has been there but now it's visible since we have increased the number of reconcile workers.

### PR DESCRIPTION
**Pull request by shayanh**
+ Added e2e test for runner pod

Fixes #794

### CODE REVIEW

File: neonvm/controllers/virtualmachine_controller.go [hunk 1]
```diff
@@ -321,6 +321,11 @@ func (r *VirtualMachineReconciler) doReconcile(ctx context.Context, virtualmachi
 	// Generate runner pod name
 	if len(virtualmachine.Status.PodName) == 0 {
 		virtualmachine.Status.PodName = names.SimpleNameGenerator.GenerateName(fmt.Sprintf("%s-", virtualmachine.Name))
+		// Update the .Status.PodName on API Server to avoid creating multiple pods for a single VM
+		// See https://github.com/neondatabase/autoscaling/issues/794 for the context
+		if err := r.Status().Update(ctx, virtualmachine); err != nil {
+			return fmt.Errorf("Failed to update .Status.PodName: %w", err)
+		}
 	}
```
Comment (sharnoff) [inline neonvm/controllers/virtualmachine_controller.go:329]: For later: When I realized the pod name was set _here_ (and not inside of the phase switch statement), I was quite surprised. We might want to move it into the handling for Pending or something.

Maybe not necessary until #733.

File: tests/e2e/runner-pod/01-assert.yaml [hunk 2]
```diff
@@ -0,0 +1,33 @@
+apiVersion: kuttl.dev/v1beta1
+kind: TestAssert
+timeout: 60
+commands:
+  - script: kubectl get pods -n "$NAMESPACE" --no-headers=true -l vm.neon.tech/name=example | [ $(wc -l) -eq 1 ]
```
Comment (sharnoff) [inline tests/e2e/runner-pod/01-assert.yaml:5]: This _may_ fail due to the PRESERVE_RUNNER_PODS env var in CI (which in turn sets the `nodelete` build tag) — basically, in order to keep VM runner pod logs available in CI, we don't delete the runner pod.

**Review by sharnoff — APPROVED** [review]
LGTM. If the test fails because we intentionally don't delete runner pods in CI, I'm happy to merge without the test.

File: tests/e2e/runner-pod/01-assert.yaml (hunk 2 above)
Comment (shayanh) [reply tests/e2e/runner-pod/01-assert.yaml:5]: I see, but still there should be only one running pod, right? I can query only the pods that are running.

Comment (sharnoff) [reply tests/e2e/runner-pod/01-assert.yaml:5]: For now, yes. With container-mgr enabled, no: the original pod will remain "running" because even though the neonvm-runner container will be killed, the the container-mgr container will still be running.

File: neonvm/controllers/virtualmachine_controller.go [hunk 3]
```diff
@@ -321,6 +321,11 @@ func (r *VirtualMachineReconciler) doReconcile(ctx context.Context, virtualmachi
 	// Generate runner pod name
 	if len(virtualmachine.Status.PodName) == 0 {
 		virtualmachine.Status.PodName = names.SimpleNameGenerator.GenerateName(fmt.Sprintf("%s-", virtualmachine.Name))
+		// Update the .Status.PodName on API Server to avoid creating multiple pods for a single VM
```
Comment (Omrigan) [inline neonvm/controllers/virtualmachine_controller.go:324]: nit: it can also update `.Status.SSHSecretName`. So technically we update not the particular field, but the entire `virtualmachine` object. Maybe the wording here and in the error message can be improved.

File: tests/e2e/runner-pod/01-assert.yaml (hunk 2 above)
Comment (Omrigan) [reply tests/e2e/runner-pod/01-assert.yaml:5]: I thought with crictl PR merged container-mgr will also be killed when runner dies, no?

File: tests/e2e/runner-pod/00-assert.yaml [hunk 4]
```diff
@@ -0,0 +1,33 @@
+apiVersion: kuttl.dev/v1beta1
```
Comment (Omrigan) [inline tests/e2e/runner-pod/00-assert.yaml:1]: Suggestion: maybe have a readme in test directory explaining what the test does? It is non-trivial how this tests .Status.PodName

**Review by Omrigan — APPROVED** [review]

File: tests/e2e/runner-pod/01-assert.yaml (hunk 2 above)
Comment (sharnoff) [reply tests/e2e/runner-pod/01-assert.yaml:5]: Basically with crictl enabled, we would have to make a choice between deleting the pod (to kill container-mgr) or leaving it running. In CI, we want to keep the runner pods around to be able to fetch their logs, which means we can't delete the pod (and therefore can't kill container-mgr).

Comment (Omrigan) [reply tests/e2e/runner-pod/01-assert.yaml:5]: Would killing container-mgr (and not the whole pod) be a soultion. Thus pod is preserved when we have `nodelete`?

Comment (sharnoff) [reply tests/e2e/runner-pod/01-assert.yaml:5]: I checked this when working on the original PR and AFAICT there isn't a clean way to kill a container within a pod — but, I'd love to find a solution :sweat_smile:

Comment (shayanh) [reply tests/e2e/runner-pod/01-assert.yaml:5]: I made it work with deleting the entire runner pod (kubectl delete). Works with both crictl and `--skip-delete` enabled.

File: neonvm/controllers/virtualmachine_controller.go (hunk 1 above)
Comment (shayanh) [reply neonvm/controllers/virtualmachine_controller.go:329]: I agree, let's leave it once we get to #733.

File: tests/e2e/runner-pod/00-assert.yaml (hunk 4 above)
Comment (shayanh) [reply tests/e2e/runner-pod/00-assert.yaml:1]: This test is broader than just testing `.Status.PodName`. We test our basic guarantees around runner pod.

File: tests/e2e/runner-pod/01-assert.yaml (hunk 2 above)
Comment (shayanh) [reply tests/e2e/runner-pod/01-assert.yaml:5]: For deleting a specific container container in a pod, you can do this: `kubectl exec <PodName> --container <ContainerName> -- kill 1`.

File: tests/e2e/runner-pod/00-assert.yaml (hunk 4 above)
Comment (Omrigan) [reply tests/e2e/runner-pod/00-assert.yaml:1]: Maybe add it as a separate commit then? For better blame.

But the suggestion still stands :laughing:
