### PR TITLE
fix iptables rules for traffic from localhost

### LINKED ISSUE #692: Bug: Cannot access NeonVM pods metrics endpoint
## Environment

local development, staging

(idk if it's the case in prod)

## Steps to reproduce

```
kubectl --context dev-us-east-2-beta port-forward compute-wispy-surf-w25ffuy9-hwvdf 9100:9100
```

and then `curl http://localhost:9100/metrics` gets stuck.

## Expected result

Seeing metrics via curl.

## Actual result

No response.

### PR DESCRIPTION
**Pull request by cicdteam**
### This PR
- adds additional `iptables` rules that allow traffic from localhost (in the runner pod) to ports on the VM.

Now possible do `kubectl port-forward vm-runner-pod-name 9100` and then run `curl localhost:9100/metrics`
 or just `kubectl exec -it vm-runner-pod-name -- curl localhost:9100/metrics`

### Internal details:

These rules will be added for port 9100 as an example

```
iptables -t nat -A OUTPUT -m addrtype --src-type LOCAL --dst-type LOCAL -p tcp --dport 9100 -j DNAT --to-destination 169.254.254.254:9100
iptables -A OUTPUT -s 127.0.0.1 -d 169.254.254.254 -p tcp --dport 9100 -j ACCEPT
```

and this rule for all ports
```
iptables -t nat -A POSTROUTING -m addrtype --src-type LOCAL --dst-type UNICAST -j MASQUERADE
```

fixes #692

### CODE REVIEW

File: neonvm/runner/main.go [hunk 1]
```diff
@@ -1137,17 +1137,50 @@ func defaultNetwork(logger *zap.Logger, cidr string, ports []vmv1.Port) (mac.MAC
...
+			"-t", "nat", "-A", "OUTPUT",
+			"-m", "addrtype", "--src-type", "LOCAL", "--dst-type", "LOCAL",
+			"-p", fmt.Sprint(port.Protocol), "--dport", fmt.Sprint(port.Port),
+			"-j", "DNAT", "--to-destination", fmt.Sprintf("%s:%d", ipVm.String(), port.Port),
+		}
+		if err := execFg("iptables", iptablesArgs...); err != nil {
+			logger.Error("could not set up DNAT rule for traffic from localhost", zap.Error(err))
+			return nil, err
+		}
+		logger.Info(fmt.Sprintf("setup ACCEPT rule for traffic originating from localhost to port %d", port.Port))
```
Comment (shayanh) [inline neonvm/runner/main.go:1163]: why do we need this accept rule here?

File: neonvm/runner/main.go [hunk 2]
```diff
@@ -1137,17 +1137,50 @@ func defaultNetwork(logger *zap.Logger, cidr string, ports []vmv1.Port) (mac.MAC
...
+		iptablesArgs = []string{
```
Comment (shayanh) [inline neonvm/runner/main.go:1164]: Why do we need the accept rule here?

**Review by shayanh — APPROVED** [review]
lgtm

File: neonvm/runner/main.go (hunk 2 above)
Comment (cicdteam) [reply neonvm/runner/main.go:1164]: it's  OUTPUT chain needed because in neon-compute we have additional iptables rules that prevent any traffic to 169.254.252.252/30
