### PR TITLE
neonvm: Custom reconciler metrics

### LINKED ISSUE #247: no observability into neonvm reconcile failures (needs metrics!)
Problems like #243 would be easier to detect and debug if we had more observability into the neonvm controller, specifically around reconciliation failures.

Off-hand, I see two ways of doing this (but there are definitely more!)

1. Increment some counter when reconciling fails (i.e. global rate of failed reconciliation)
2. Globally track how many VMs are failing to reconcile, expose this as a gague
    - This is more work (and uses more memory, and has the "multiple sources of truth" problem), but is maybe closer to what we actually care about.

We can also do both options, because each option has cases that it will report but the other won't.

### PR DESCRIPTION
**Pull request by shayanh**
Providing custom metrics for reconciler objects.

- `reconcile_failing_objects` represents the number of objects that are failing to reconcile for each specific controller.

Fixes #247 (along with #739).

### CODE REVIEW

File: neonvm/controllers/metrics.go [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+
+func (d *wrappedReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
+	res, err := d.Reconciler.Reconcile(ctx, req)
+
+	// This part is executed sequentially since we acquire a mutex lock. It
+	// should be quite fast since a mutex lock/unlock + 1 memory write takes
+	// ~60ns. Having 8 reconile workers, we wait at most 8*60=480ns to acquire
+	// the lock. I (@shayanh) preferred to go with the simplest implementation
+	// as of now. For a more performant solution, if needed, we can switch to an
+	// async approach.
```
Comment (sharnoff) [inline neonvm/controllers/metrics.go:60]: fwiw, I think it's more than "1 memory write" — hashmap access plus whatever `WithLabelValues(..).Set(..)` does is probably non-trivial.
But yeah, as long as we're not holding a mutex while doing IO we should be good :)

File: neonvm/controllers/metrics.go [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+	d.lock.Lock()
+	defer d.lock.Unlock()
+	if err != nil {
+		d.failing[req.NamespacedName] = struct{}{}
```
Comment (sharnoff) [inline neonvm/controllers/metrics.go:64]: Is it possible for an object to be deleted while still failing? (maybe with `kubectl delete --force`?)

If not, it'd be good to have a brief explainer why. If so, any ideas how we can avoid false positives in the failing count?

File: neonvm/controllers/virtualmachine_controller.go [hunk 3]
```diff
@@ -74,6 +74,8 @@ type VirtualMachineReconciler struct {
 	client.Client
 	Scheme   *runtime.Scheme
 	Recorder record.EventRecorder
+
+	Metrics ReconcilerMetrics `exhaustruct:"optional"`
```
Comment (sharnoff) [inline neonvm/controllers/virtualmachine_controller.go:78]: TIL there's exhaustruct struct tags - nice! :D

Comment (sharnoff) [reply neonvm/controllers/virtualmachine_controller.go:78]: Is there a reason why it's needed here and not for `VirtualMachineMigrationReconciler` ?

File: neonvm/controllers/virtualmachinemigration_controller.go [hunk 4]
```diff
@@ -666,11 +668,14 @@ func (r *VirtualMachineMigrationReconciler) doFinalizerOperationsForVirtualMachi
...
 // desirable state on the cluster
 func (r *VirtualMachineMigrationReconciler) SetupWithManager(mgr ctrl.Manager) error {
+	cntrlName := "virtualmachinemigration"
+	reconciler := WithMetrics(r, r.Metrics, cntrlName)
 	return ctrl.NewControllerManagedBy(mgr).
 		For(&vmv1.VirtualMachineMigration{}).
 		Owns(&corev1.Pod{}).
 		WithOptions(controller.Options{MaxConcurrentReconciles: 8}).
-		Complete(r)
+		Named(cntrlName).
```
Comment (sharnoff) [inline neonvm/controllers/virtualmachinemigration_controller.go:677]: not a blocker: what's the impact of `Named` here?

File: neonvm/controllers/virtualmachine_controller.go (hunk 3 above)
Comment (shayanh) [reply neonvm/controllers/virtualmachine_controller.go:78]: It's because of tests. There is a test that we have initialized a `VirtualMachineReconciler`.

File: neonvm/controllers/virtualmachinemigration_controller.go (hunk 4 above)
Comment (shayanh) [reply neonvm/controllers/virtualmachinemigration_controller.go:677]: Sets the name of the controller. Its used in metrics particularly.

https://github.com/kubernetes-sigs/controller-runtime/blob/b88ed7a3602b85b6cfd0acfe9c25033b978bdb83/pkg/builder/controller.go#L210-L214

File: neonvm/controllers/metrics.go (hunk 1 above)
Comment (shayanh) [reply neonvm/controllers/metrics.go:60]: I forgot about `WithLabelValues(..).Set(..)` but it's an `atomic.StoreUint64`.

File: neonvm/controllers/metrics.go (hunk 2 above)
Comment (shayanh) [reply neonvm/controllers/metrics.go:64]: I think if an object is deleted then it still goes through the `Reconcile` function but we treat it differently.

https://github.com/neondatabase/autoscaling/blob/ac66e2c7b11e7a8fd209f300a208de5d2003585a/neonvm/controllers/virtualmachine_controller.go#L140-L158

Comment (sharnoff) [reply neonvm/controllers/metrics.go:63]: Is that still guaranteed for `--force` ?

File: neonvm/controllers/virtualmachinemigration_controller.go (hunk 4 above)
Comment (sharnoff) [reply neonvm/controllers/virtualmachinemigration_controller.go:677]: Ah fair enough - so this is more a continuation of #739?

File: neonvm/controllers/metrics.go (hunk 1 above)
Comment (sharnoff) [reply neonvm/controllers/metrics.go]: Hm, I appreciate the concern for efficiency. In this case, I'd recommend dropping the exact numbers — the metrics handling isn't trivial¹ and IMO it's not worth it to actually collect exact timings. Either way though, I'd be shocked if manipulating the metrics was a bottleneck, given the number of http requests we make while reconciling :sweat_smile:

---

¹ For example, in the case where the metric already exists, we still end up calling:

- [`(*GaugeVec).GetMetricWithLabelValues()`](https://github.com/prometheus/client_golang/blob/v1.14.0/prometheus/gauge.go#L182-L188)
  - [`(*MetricVec).GetMetricWithLabelValues()`](https://github.com/prometheus/client_golang/blob/v1.14.0/prometheus/vec.go#L201-L208)
    - [`(*MetricVec).hashLabelValues()`](https://github.com/prometheus/client_golang/blob/v1.14.0/prometheus/vec.go#L235-L256) (
      - [`validateLabelValues`](https://github.com/prometheus/client_golang/blob/v1.14.0/prometheus/labels.go#L68-L84) (should be relatively cheap)
      - `(*MetricVec).hashAdd{,Byte}` (internally [`hashAdd`](https://github.com/prometheus/client_golang/blob/v1.14.0/prometheus/fnv.go#L29-L42)) (computes FNV64a hash of the label value(s) - realistically, pretty cheap, but non-zero)
    - [`(*metricMap).getOrCreateMetricWithLabelValues()`](https://github.com/prometheus/client_golang/blob/v1.14.0/prometheus/vec.go#L474-L493) (does RWMutex lock/unlock)
      - [`(*metricMap).getMetricWithHashAndLabelValues()`](https://github.com/prometheus/client_golang/blob/v1.14.0/prometheus/vec.go#L522-L532) (does hashmap lookup)
        - [`findMetricWithlabelValues()`](https://github.com/prometheus/client_golang/blob/v1.14.0/prometheus/vec.go#L550-L559) (iterates through hashmap bucket - should be n=1)
          - [`matchLabelValues()`](https://github.com/prometheus/client_golang/blob/v1.14.0/prometheus/vec.go#L574-L593) (somewhat complex control flow, but should be pretty cheap for 1 label value, not too long)

[^examples]: For example, in the case where the metric already exists, we still end up transitively calling `(*GaugeVec).GetMetricWithLabelValues()` → `

Comment (shayanh) [reply neonvm/controllers/metrics.go]: You're right. The set is the `atomic.StoreUint64`. I already removed the numbers from the comment.

File: neonvm/controllers/virtualmachinemigration_controller.go (hunk 4 above)
Comment (shayanh) [reply neonvm/controllers/virtualmachinemigration_controller.go:677]: Right, I want to expose the metrics in the same format at kubebuilder does.

File: neonvm/controllers/metrics.go (hunk 2 above)
Comment (shayanh) [reply neonvm/controllers/metrics.go:63]: Yes, `kubectl --force` doesn't wait for confirmation. It's a client-side behaviour. More info: https://kubernetes.io/docs/reference/kubectl/generated/kubectl_delete/

Comment (sharnoff) [reply neonvm/controllers/metrics.go:63]: Tried it out locally and I see that `--force` still respects the finalizer; fair enough

**Review by sharnoff — APPROVED** [review]
