### PR TITLE
plugin: Add pod desired AZ to plugin method metrics

### LINKED ISSUE #861: scheduler plugin's failed scheduling metrics should include preferred AZ of the pod, if available
## Problem description / Motivation

From the current metrics related to scheduling failures (`PostFilter` and `Unreserve` method calls), it's hard to tell the scope of any impact. Being able to see the affected AZs would significantly help with after-the-fact analysis and in-the-moment triage.

## Feature idea(s) / DoD

Relevant scheduler metrics have a label for the availability zone. We _may_ also want to consider node and node group labels. We may also want to survey the other metrics we expose, to see if they'd benefit from these labels as well.

### PR DESCRIPTION
**Pull request by sharnoff**
- Adds `util.PodPreferredAZIfPresent` to determine the AZ
- Adds the `desired_availability_zone` label to the plugin method metrics
- Passes the `*corev1.Pod` through to `IncMethodCall` and `IncFailIfNotSuccess` to inclulde the AZ

Closes #861.

### CODE REVIEW

File: pkg/util/k8s.go [hunk 1]
```diff
@@ -30,6 +30,47 @@ func PodStartedBefore(p, q *corev1.Pod) bool {
 	return p.Status.StartTime.Before(q.Status.StartTime)
 }
 
+// TryPodPreferredAZ returns the desired availability zone of the Pod, if it has one
+func TryPodPreferredAZ(pod *corev1.Pod) string {
```
Comment (shayanh) [inline pkg/util/k8s.go:34]: The naming here that starts with "try" is a little bit confusing. If you want to emphasize that the preferred AZ might not exist, might it would be better to rename to `PodPreferredAZIfPresent`.

**Review by shayanh — APPROVED** [review]
lgtm!

File: pkg/util/k8s.go (hunk 1 above)
Comment (sharnoff) [reply pkg/util/k8s.go]: Fair enough, makes sense - done

File: pkg/util/k8s.go [hunk 2]
```diff
@@ -30,6 +30,47 @@ func PodStartedBefore(p, q *corev1.Pod) bool {
...
 
+// PodPreferredAZIfPresent returns the desired availability zone of the Pod, if it has one
+func PodPreferredAZIfPresent(pod *corev1.Pod) string {
+	if pod.Spec.Affinity == nil || pod.Spec.Affinity.NodeAffinity == nil {
+		return ""
+	}
+
+	affinity := pod.Spec.Affinity.NodeAffinity
+
+	azForTerm := func(term corev1.NodeSelectorTerm) string {
```
Comment (Omrigan) [inline pkg/util/k8s.go:41]: Can this function be standalone? If so, I'd prefer that way, it's more natural.

**Review by Omrigan — APPROVED** [review]

File: pkg/util/k8s.go (hunk 2 above)
Comment (sharnoff) [reply pkg/util/k8s.go]: Fair enough, done
