### PR TITLE
neonvm: Add support for virtio-mem

### LINKED ISSUE #117: Impossible to scale memory more than x60
Original title: "vhost backends exhausted"

## Steps to reproduce
related to large VMs

## Logs, links
-

### LINKED ISSUE #967: Bug: neonvm-controller spams new pod names when VM fails and RestartPolicy = Never
## Environment

Local development (not staging/prod because we have RestartPolicy = Always there)

## Steps to reproduce

Using `vm-deploy.yaml`, set `spec.restartPolicy: Never` and then `kill -6 1` inside the runner pod (`kill -9` doesn't work).

```diff
diff --git a/vm-deploy.yaml b/vm-deploy.yaml
index 09588f6..7d84d67 100644
--- a/vm-deploy.yaml
+++ b/vm-deploy.yaml
@@ -13,6 +13,7 @@ metadata:
 spec:
   schedulerName: autoscale-scheduler
   enableSSH: true
+  restartPolicy: Never
   guest:
     cpus: { min: 0.25, use: 0.25, max: 1.25 }
     memorySlotSize: 1Gi
```

```sh
kubectl exec postgres16-disk-test-<SUFFIX> -- kill -6 1
```

## Expected result

The pod name should either:

1. Remain what it was when the VM failed; or
2. Remain set to `""` until the VM is deleted

There are good arguments for both cases here, I think.

## Actual result

If you `kubectl get -w neonvm` while using the reproduction steps above, you'll see a rapid stream of changes that looks something like:

```sh-session
$ kubectl get -w neonvm
NAME                   CPUS   MEMORY   POD                          EXTRAIP   STATUS    RESTARTS   AGE
postgres16-disk-test   250m   1Gi      postgres16-disk-test-j5sb8             Running              14s
postgres16-disk-test   250m   1Gi      postgres16-disk-test-j5sb8             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-mpl6w             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-pdh8f             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-zzzm6             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-9qfcm             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-nq4vf             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-dwml5             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-r78fc             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-965jp             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-fqmxd             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-zgnrv             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-bcpw7             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-ck9kz             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-m9n97             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-h46sz             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-x49h7             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-dqhss             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-mc6xm             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-zh682             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-r87cv             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-ldmhd             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-mqfrb             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-gs8pc             Failed               38s
postgres16-disk-test                                                          Failed               38s
postgres16-disk-test                   postgres16-disk-test-8twbx             Failed               38s
```

## Other logs, links

- ...

### PR DESCRIPTION
**Pull request by sharnoff**
Adapted from #705.

This implementation is focused on making virtio-mem a drop-in replacement for our existing DIMM hotplug -based memory scaling.

As such, the externally visible differences are:

1. VirtualMachines have a new optional field: `.spec.guest.memoryProvider`
2. VirtualMachines have a new optional field: `.status.memoryProvider`
3. VirtualMachine `.status.memorySize` changes in smaller increments if using virtio-mem.

This change introduces the concept of a "memory provider", which is either "DIMMSlots" or "VirtioMem".

If a VM is created without setting the memory provider in the spec, the controller will use the default one, which is specified by its `--default-memory-provider` flag.
This will only persist for the lifetime of the runner pod. If the VM is restarted, then it may change to a new default.

Additionally, because our usage of virtio-mem has 8MiB block sizes, we actually *don't* default to virtio-mem if the VM was created with some odd memory slot size that isn't divisible by 8MiB.

The memory provider of the current runner pod is stored in the new status field. For old VMs created before this change, the status field is set to DIMMSlots iff the pod name is set without the status field.

Also, we allow mutating `.spec.guest.memoryProvider` IFF it is being set equal to the current `.status.memoryProvider`, in case we we want old VMs to keep their dimm slots after switching to virtio-mem by default.

---

Changes to split out from this PR:

1. #971
2. #973
3. #974

On top of those, there's a couple places where code was indented that should probably be split into its own commit so it can be properly added to .git-blame-ignore-revs :)

---

Remaining testing for this PR before merging:

- [x] Test that backwards compatibility works as expected
   - [x] Old VMs are updated while running as described above
   - [x] Old VMs switch to the new default on restart
- [x] Test rollback safety: that it's ok to go between the last release and this PR (with `--default-memory-provider=DIMMSlots`).
   - Note: If `--default-memory-provider=VirtioMem` when this is released, we cannot make it rollback-safe.
- [ ] ~~Test that updating `.spec.guest.memoryProvider` works as expected~~

---

Future/follow-up work:

1. #981
2. Switch to virtio-mem by default
3. Remove support for DIMM hotplug
4. Move from representing memory as "memory slots" towards the implementation
5. Fix the raciness issue with migration target pod creation.

### CODE REVIEW

**Review by Omrigan — COMMENTED** [review]
Just a couple thoughts

**Comment by sharnoff** [comment]
Cleaned up the commits in this PR -- added single commits for #973 and #974, and split some indenting into a separate commit. May move more indenting, need to see.

Anyways, hopefully should make the final commit easier to review :crossed_fingers:

File: neonvm/apis/neonvm/v1/virtualmachine_types.go [hunk 1]
```diff
@@ -558,6 +604,7 @@ func (vm *VirtualMachine) Cleanup() {
 	vm.Status.Node = ""
 	vm.Status.CPUs = nil
 	vm.Status.MemorySize = nil
+	vm.Status.MemoryProvider = nil
```
[the remark this answers is not in the document]
Comment (sharnoff) [reply neonvm/apis/neonvm/v1/virtualmachine_types.go:599]: There's a couple reasons I went for this approach. This was my thought process, lmk what you think:

1. We need _some_ way to know how to scale the memory on the runner pod. This can either be a field in the spec or status.
2. We don't want to _need_ the control plane to set it; that way, we get control over rollout. So, as you mentioned -- either spec or status, but we have to auto-set _something_.
3. IMO: We should have an escape hatch, once virtio-mem is deployed. I.e., for a particular VM, we should be able to say "hey, please use DIMM slots instead". Eventually this should be a project/endpoint/compute setting (until we decide it's stable enough), and then we can remove all the old code. This belongs in the spec.
4. IMO: Once the VM is up and running, we _shouldn't_ allow changes to MemoryProvider setting. Actually, it needs to be _before_ the VM is up and running, to prevent race conditions. This can either be done with a status field (because special permissions are required), or with webhook update validation (i.e. only allow updates if pending and the podName wasn't set). We've had [issues around rollout of new fields + webhook validation in the past](https://www.notion.so/neondatabase/d66861b2d8a8444887282d8558428791?pvs=4#3ddf05468a8a44378b4c9931ad3dca95), so I'm hesitant to go that route.
5. IMO: _it would be nice_ if forcing VMs to pick up a change in MemoryProvider could just be done by deleting the pods. Otherwise we have to do object "delete + recreate with modified spec" (which is kind of a pain). I'm thinking of e.g. "oh no, there's an issue with virtio-mem, we need to switch out all affected runner pods". This requires a separate field in the status, if we also want to respect the spec.
6. IMO: _it would be nice_ if we could avoid neonvm-controller updating the spec (because I view "spec" as kind of "here's what the user asked", so to me it feels a little odd to update the spec. but... we have defaults anyways, so maybe this is analogous to that?)

From going through it again, I think it would be _fine_ to just use the spec, but I do also like having the status be separate. With (5) I'm probably just being paranoid.

WDYT?

File: neonvm/apis/neonvm/v1/virtualmachine_webhook.go [hunk 2]
```diff
@@ -187,6 +195,19 @@ func (r *VirtualMachine) ValidateUpdate(old runtime.Object) error {
 		}
 	}
 
+	// Only allow changing .spec.guest.memoryProvider if it was previously nil, and the new version
+	// is equal to .status.memoryProvider.
+	if !reflect.DeepEqual(before.Spec.Guest.MemoryProvider, r.Spec.Guest.MemoryProvider) {
```
[the remark this answers is not in the document]
Comment (sharnoff) [reply neonvm/apis/neonvm/v1/virtualmachine_webhook.go]: Yeah fair enough. Done in 072fe6a130bb1884f79319ec68d0452d92935c4b. Won't squash until the discussion below is resolved, because IIUC we'll have to make this mutable if we put MemoryProvider in the spec, to allow neonvm-controller to set it

**Comment by sharnoff** [comment]
Did backwards-compatibility testing locally (started a VM, upgraded the version, checked status was as expected, assuming that our existing e2e tests can take it from there). Found & fixed a bug.
Also checked rollback safety; yeah, seems fine :)
One interesting thing, posted it here: https://neondb.slack.com/archives/C039YKBRZB4/p1718950172991649

File: neonvm/controllers/vm_controller.go [hunk 3]
```diff
@@ -715,41 +729,71 @@ func (r *VMReconciler) doReconcile(ctx context.Context, vm *vmv1.VirtualMachine)
...
+				if targetVirtioMemSize < previousTarget {
+					reason = "ScaleDown"
+				}
+				r.Recorder.Eventf(vm, "Normal", reason, "Set virtio-mem size for %v total memory", goalTotalSize)
+			}
+
+			// Maybe we're already using the amount we want?
+			// Update the status to reflect the current size - and if it matches goalTotalSize, ram
+			// is done.
+			currentTotalSize, err := QmpGetMemorySize(QmpAddr(vm))
```
Comment (Omrigan) [inline neonvm/controllers/vm_controller.go:764]: I think this is a redundant check, we could get the current memory size from where it is set. 

But no worries, I'll clean it up in #943

File: neonvm/controllers/vm_controller.go [hunk 4]
```diff
@@ -715,41 +729,71 @@ func (r *VMReconciler) doReconcile(ctx context.Context, vm *vmv1.VirtualMachine)
...
+				reason := "ScaleUp"
+				if targetVirtioMemSize < previousTarget {
+					reason = "ScaleDown"
+				}
+				r.Recorder.Eventf(vm, "Normal", reason, "Set virtio-mem size for %v total memory", goalTotalSize)
+			}
+
+			// Maybe we're already using the amount we want?
+			// Update the status to reflect the current size - and if it matches goalTotalSize, ram
+			// is done.
```
Comment (Omrigan) [inline neonvm/controllers/vm_controller.go:763]:
```suggestion
			// scaling is done.
```

File: neonvm/controllers/vm_controller.go [hunk 5]
```diff
@@ -812,6 +861,23 @@ func (r *VMReconciler) doReconcile(ctx context.Context, vm *vmv1.VirtualMachine)
 	return nil
 }
 
+func pickMemoryProvider(config *ReconcilerConfig, vm *vmv1.VirtualMachine) vmv1.MemoryProvider {
+	if p := vm.Spec.Guest.MemoryProvider; p != nil {
+		return *p
+	}
+	if p := vm.Status.MemoryProvider; p != nil {
```
Comment (Omrigan) [inline neonvm/controllers/vm_controller.go:868]: Won't this prevent us from changing from one provider to the other by deleting the pod, because the old value be preserved through Status?

File: neonvm/controllers/vm_qmp_queries.go [hunk 6]
```diff
@@ -333,6 +333,65 @@ type QMPRunner interface {
...
+// If the new target size is equal to the previous one, this function does nothing but query the
+// target.
+func QmpSetVirtioMem(vm *vmv1.VirtualMachine, targetVirtioMemSize int64) (previous int64, _ error) {
+	// Note: The virtio-mem device only exists when max mem != min mem.
+	// So if min == max, we should just short-cut, skip the queries, and say it's all good.
+	// Refer to the instantiation in neonvm-runner for more.
+	if vm.Spec.Guest.MemorySlots.Min == vm.Spec.Guest.MemorySlots.Max {
+		// if target size is non-zero even though min == max, something went very wrong
+		if targetVirtioMemSize != 0 {
+			panic(fmt.Errorf(
```
Comment (Omrigan) [inline neonvm/controllers/vm_qmp_queries.go:347]:
```suggestion
			panic(fmt.Sprintf(
```

Usually panic's arg is the string.

File: tests/e2e/autoscaling.virtio-mem/01-assert.yaml [hunk 7]
```diff
@@ -0,0 +1,23 @@
+apiVersion: kuttl.dev/v1beta1
+kind: TestAssert
+timeout: 90
+---
+apiVersion: vm.neon.tech/v1
+kind: VirtualMachine
+metadata:
+  name: example
+status:
```
Comment (Omrigan) [inline tests/e2e/autoscaling.virtio-mem/01-assert.yaml:9]: can we assert on the provider here?

**Review by Omrigan — APPROVED** [review]
Looks good overall

File: neonvm/controllers/vm_controller.go (hunk 3 above)
Comment (sharnoff) [reply neonvm/controllers/vm_controller.go:764]: I _think_ in testing I actually saw this value change in between QMP queries in the same reconcile cycle. Not totally sure though...

File: neonvm/controllers/vm_controller.go (hunk 5 above)
Comment (sharnoff) [reply neonvm/controllers/vm_controller.go:868]: the tl;dr on that is that we reset `.status.memoryProvider` in the same place we reset `.status.podName` (there's some method on `VirtualMachineStatus` that does it for us).

I tested it locally and it works as expected :)

File: neonvm/controllers/vm_controller.go [hunk 8]
```diff
@@ -359,16 +366,23 @@ func (r *VMReconciler) doReconcile(ctx context.Context, vm *vmv1.VirtualMachine)
 		// VirtualMachine just created, change Phase to "Pending"
 		vm.Status.Phase = vmv1.VmPending
 	case vmv1.VmPending:
-		// Generate runner pod name
+		// Generate runner pod name and set desired memory provider. After this, we know that
+		// MemoryProvider will be set, because earlier (above the 'switch vm.Status.Phase'), we set
+		// the MemoryProvider iff PodName was set but it wasn't.
```
[the remark this answers is not in the document]
Comment (sharnoff) [reply neonvm/controllers/vm_controller.go:371]: Nice - I like that a lot better :)

File: tests/e2e/autoscaling.virtio-mem/01-assert.yaml (hunk 7 above)
Comment (sharnoff) [reply tests/e2e/autoscaling.virtio-mem/01-assert.yaml:9]: Done

File: neonvm/controllers/vm_controller.go [hunk 9]
```diff
@@ -722,38 +722,38 @@ func (r *VMReconciler) doReconcile(ctx context.Context, vm *vmv1.VirtualMachine)
...
-		if realSlots < 0 {
-			return err
-		}
-
-		if realSlots != int(targetSlotCount) {
-			log.Info("Couldn't achieve desired memory slot count, will modify .spec.guest.memorySlots.use instead", "details", err)
-			// firstly re-fetch VM
-			if err := r.Get(ctx, types.NamespacedName{Name: vm.Name, Namespace: vm.Namespace}, vm); err != nil {
-				log.Error(err, "Unable to re-fetch VirtualMachine")
+			realSlots, err := QmpSetMemorySlots(ctx, vm, targetSlotCount, r.Recorder)
```
[the remark this answers is not in the document]
Comment (sharnoff) [reply neonvm/controllers/vm_controller.go]: Extracted in d2b8d897c917835790acb35b157e2833a6109d0d, replaced the indent commit with 1f05547e8c0f88e361229556fcd5b695a69b40d2 (splitting the first commit).
